# Generated by Django 2.2.12 on 2020-06-18 17:44

from django.db import migrations, models
import sortedm2m.fields


class Migration(migrations.Migration):

    dependencies = [
        ('course_metadata', '0250_auto_20200518_2054'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='collaborator_images',
            field=sortedm2m.fields.SortedManyToManyField(blank=True, help_text=None, related_name='collaborator_images', to='course_metadata.Image'),
        ),
        migrations.AlterField(
            model_name='leveltypetranslation',
            name='name_t',
            field=models.CharField(max_length=255, verbose_name='name'),
        ),
    ]
